# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 19:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2017, 3, 26, 19, 58, 35, 632756, tzinfo=utc))),
            ],
        ),
    ]
